Update sab-cheker-cl20.yml
ghjjj

diff --git a/.github/workflows/sab-cheker-cl20.yml b/.github/workflows/sab-cheker-cl20.yml
--- a/.github/workflows/sab-cheker-cl20.yml
+++ b/.github/workflows/sab-cheker-cl20.yml
@@ -1,15 +1,15 @@
-name: Sub Checker CL20
+name: Sub Checker CL100
 
 on:
   workflow_dispatch:
   schedule:
-    - cron: "0 */8 * * *"   # اجرای cl20.py هر ۱ ساعت
+    - cron: "*/18 * * * *"   # اجرای cl20.py هر ۱ ساعت
 
 permissions:
   contents: write
 
 jobs:
-  cl20-job:
+  cl100-job:
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
@@ -19,15 +19,15 @@ jobs:
           python-version: 3.11
       - run: pip install requests psutil retrying PyYaml || echo "skip install"
       - run: |
-          rm -f final20.txt normal20.txt
-          timeout 300s python cl20.py || echo "❌ cl20.py failed or skipped"
+          rm -f final20.txt normal100.txt
+          timeout 300s python cl100.py || echo "❌ cl100.py failed or skipped"
       - run: |
-          if [[ -s final20.txt || -s normal20.txt ]]; then
+          if [[ -s final100.txt || -s normal100.txt ]]; then
             git config user.name "github-actions[bot]"
             git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-            git add final20.txt normal20.txt
-            git commit -m "auto update from cl20.py [skip ci]" || echo "No changes"
+            git add final1000.txt normal100.txt
+            git commit -m "auto update from cl100.py [skip ci]" || echo "No changes"
             git push || echo "skip push"
           else
-            echo "⚠️ final20.txt یا normal20.txt خالی یا موجود نیست، commit نشد"
+            echo "⚠️ final100.txt یا normal100.txt خالی یا موجود نیست، commit نشد"
           fi
